name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
     runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.repository }}:latest
      env:
        DOCKER_BUILDKIT: 1

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Connect to AKS
      run: az aks get-credentials --resource-group rg-ssib-imssbienestar-qa-aks-01 --name aks-mxce-qa-aks-01

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/Prueba01
